/**
 * OpenSearch index template definitions for all 10 cognitive memory indexes.
 * Each schema is expressed as a plain object that can be passed directly
 * to the OpenSearch Indices API.
 *
 * Embedding dimension defaults to 1536 (OpenAI text-embedding-3-small).
 * Override via the EMBEDDING_DIMENSION environment variable when using
 * an alternative embedding model.
 */

const EMBEDDING_DIM: number = parseInt(process.env["EMBEDDING_DIMENSION"] ?? "1536", 10);
export const QUALITY_EMBEDDING_DIM: number = parseInt(process.env["QUALITY_EMBEDDING_DIMENSION"] ?? "1024", 10);
export const EFFICIENT_EMBEDDING_DIM: number = parseInt(process.env["EFFICIENT_EMBEDDING_DIMENSION"] ?? "768", 10);
export const HYBRID_EMBEDDING_DIM: number = parseInt(process.env["HYBRID_EMBEDDING_DIMENSION"] ?? "1024", 10);

interface KnnVectorField {
  readonly type: "knn_vector";
  readonly dimension: number;
  readonly method: {
    readonly name: "hnsw";
    readonly engine: "faiss";
    readonly space_type: "l2";
    readonly parameters: {
      readonly m: number;
      readonly ef_construction: number;
    };
  };
}

const knnVectorField = (dimension: number = EMBEDDING_DIM): KnnVectorField => ({
  type: "knn_vector",
  dimension,
  method: {
    name: "hnsw",
    engine: "faiss",
    space_type: "l2",
    parameters: { m: 16, ef_construction: 128 },
  },
});

const profileVectorFields = {
  embedding_qwen: knnVectorField(QUALITY_EMBEDDING_DIM),
  embedding_nomic: knnVectorField(EFFICIENT_EMBEDDING_DIM),
  embedding_bge_m3: knnVectorField(HYBRID_EMBEDDING_DIM),
} as const;

const embeddingMetaField = {
  type: "object",
  dynamic: false,
  properties: {
    profile_id: { type: "keyword" },
    model_name: { type: "keyword" },
    dimension: { type: "integer" },
    lane: { type: "keyword" },
    indexed_at: { type: "date" },
    profiles: {
      type: "nested",
      properties: {
        profile_id: { type: "keyword" },
        model_name: { type: "keyword" },
        dimension: { type: "integer" },
        lane: { type: "keyword" },
        vector_field: { type: "keyword" },
        provider: { type: "keyword" },
      },
    },
  },
} as const;

/** Raw episodic event metadata (object storage holds the full payload). */
export const experienceEventsSchema = {
  settings: {
    index: {
      knn: true,
      number_of_shards: 3,
      number_of_replicas: 1,
      "knn.algo_param.ef_search": 100,
    },
  },
  mappings: {
    properties: {
      event_id: { type: "keyword" },
      timestamp: { type: "date" },
      event_type: { type: "keyword" },
      session_id: { type: "keyword" },
      user_id: { type: "keyword" },
      agent_id: { type: "keyword" },
      summary: { type: "text", analyzer: "english" },
      embedding: knnVectorField(),
      ...profileVectorFields,
      embedding_meta: embeddingMetaField,
      importance_score: { type: "float" },
      reward_score: { type: "float" },
      confidence: { type: "float" },
      retrieval_count: { type: "integer" },
      retrieval_priority: { type: "float" },
      decay_factor: { type: "float" },
      reinforcement_score: { type: "float" },
      object_storage_key: { type: "keyword" },
      tags: { type: "keyword" },
    },
  },
} as const;

/** Consolidated semantic abstractions generated by the consolidation engine. */
export const memorySemanticSchema = {
  settings: { index: { knn: true, number_of_shards: 3, number_of_replicas: 1 } },
  mappings: {
    properties: {
      memory_id: { type: "keyword" },
      created_at: { type: "date" },
      summary: { type: "text", analyzer: "english" },
      generalization: { type: "text", analyzer: "english" },
      embedding: knnVectorField(),
      ...profileVectorFields,
      embedding_meta: embeddingMetaField,
      source_event_ids: { type: "keyword" },
      importance_score: { type: "float" },
      stability_score: { type: "float" },
      contradiction_score: { type: "float" },
      semantic_cluster: { type: "keyword" },
      usage_frequency: { type: "float" },
      retrieval_priority: { type: "float" },
      decay_factor: { type: "float" },
      reinforcement_score: { type: "float" },
      last_retrieved: { type: "date" },
    },
  },
} as const;

/** Behavioral policy drift snapshots. */
export const policyStateSchema = {
  settings: { index: { number_of_shards: 1, number_of_replicas: 1 } },
  mappings: {
    properties: {
      policy_id: { type: "keyword" },
      timestamp: { type: "date" },
      retrieval_bias: { type: "float" },
      tool_bias: { type: "float" },
      risk_tolerance: { type: "float" },
      memory_trust: { type: "float" },
      exploration_factor: { type: "float" },
      goal_persistence: { type: "float" },
      working_memory_decay_rate: { type: "float" },
      source_experience_id: { type: "keyword" },
      source_cluster_id: { type: "keyword" },
      reward_delta: { type: "float" },
    },
  },
} as const;

/** Multi-agent reasoning traces. */
export const agentActivitySchema = {
  settings: { index: { knn: true, number_of_shards: 3, number_of_replicas: 1 } },
  mappings: {
    properties: {
      trace_id: { type: "keyword" },
      timestamp: { type: "date" },
      agent_type: { type: "keyword" },
      input_summary: { type: "text" },
      proposed_action: { type: "text" },
      confidence: { type: "float" },
      score: { type: "float" },
      selected: { type: "boolean" },
      critique: { type: "text" },
      embedding: knnVectorField(),
    },
  },
} as const;

/** World-model simulation predictions and their observed accuracy. */
export const worldModelPredictionsSchema = {
  settings: { index: { number_of_shards: 2, number_of_replicas: 1 } },
  mappings: {
    properties: {
      prediction_id: { type: "keyword" },
      timestamp: { type: "date" },
      current_state_summary: { type: "text" },
      action_summary: { type: "text" },
      predicted_outcome: { type: "text" },
      risk_score: { type: "float" },
      confidence: { type: "float" },
      actual_outcome_reference: { type: "keyword" },
      prediction_accuracy: { type: "float" },
    },
  },
} as const;

/** Long-horizon goal hierarchy. */
export const goalSystemSchema = {
  settings: { index: { number_of_shards: 1, number_of_replicas: 1 } },
  mappings: {
    properties: {
      goal_id: { type: "keyword" },
      created_at: { type: "date" },
      goal_description: { type: "text" },
      goal_horizon: { type: "keyword" },
      priority: { type: "float" },
      progress: { type: "float" },
      status: { type: "keyword" },
      parent_goal_id: { type: "keyword" },
      associated_memory_ids: { type: "keyword" },
    },
  },
} as const;

/** Persistent behavioral identity state. */
export const identityStateSchema = {
  settings: { index: { number_of_shards: 1, number_of_replicas: 1 } },
  mappings: {
    properties: {
      identity_id: { type: "keyword" },
      timestamp: { type: "date" },
      curiosity: { type: "float" },
      caution: { type: "float" },
      verbosity: { type: "float" },
      tool_dependence: { type: "float" },
      exploration_preference: { type: "float" },
      stability_score: { type: "float" },
    },
  },
} as const;

/** Self-modification mutation history. */
export const selfModificationsSchema = {
  settings: { index: { number_of_shards: 1, number_of_replicas: 1 } },
  mappings: {
    properties: {
      mutation_id: { type: "keyword" },
      timestamp: { type: "date" },
      mutation_type: { type: "keyword" },
      description: { type: "text" },
      expected_gain: { type: "float" },
      observed_gain: { type: "float" },
      stability_risk: { type: "float" },
      approved: { type: "boolean" },
      rollback_available: { type: "boolean" },
    },
  },
} as const;

/** Association graph edges between memories. */
export const memoryLinksSchema = {
  settings: { index: { number_of_shards: 2, number_of_replicas: 1 } },
  mappings: {
    properties: {
      link_id: { type: "keyword" },
      source_memory_id: { type: "keyword" },
      target_memory_id: { type: "keyword" },
      relationship_type: { type: "keyword" },
      strength: { type: "float" },
      created_at: { type: "date" },
    },
  },
} as const;

/** Retrieval feedback for reinforcement learning over memory access patterns. */
export const retrievalFeedbackSchema = {
  settings: { index: { number_of_shards: 2, number_of_replicas: 1 } },
  mappings: {
    properties: {
      feedback_id: { type: "keyword" },
      timestamp: { type: "date" },
      query_summary: { type: "text" },
      retrieved_memory_id: { type: "keyword" },
      used_in_response: { type: "boolean" },
      helpfulness_score: { type: "float" },
      hallucination_detected: { type: "boolean" },
      future_weight_adjustment: { type: "float" },
    },
  },
} as const;

/**
 * System-agnostic operational patterns learned by the pattern worker.
 * Each document is deliberately free of vendor or system-specific naming:
 * the signature and precursors reference OperationalPrimitive enum values
 * only, making the index portable across infrastructure environments.
 */
export const operationalPatternsSchema = {
  settings: {
    index: {
      knn: true,
      number_of_shards: 2,
      number_of_replicas: 1,
      "knn.algo_param.ef_search": 64,
    },
  },
  mappings: {
    properties: {
      pattern_id: { type: "keyword" },
      created_at: { type: "date" },
      updated_at: { type: "date" },
      signature: { type: "keyword" },
      precursors: { type: "keyword" },
      outcome: { type: "text", analyzer: "english" },
      interventions: { type: "keyword" },
      confidence: { type: "float" },
      observation_count: { type: "integer" },
      success_count: { type: "integer" },
      description_embedding: knnVectorField(),
    },
  },
} as const;

/** Immutable mirrored cognitive events consumed from the audit Kafka topic. */
export const auditEventsSchema = {
  settings: { index: { number_of_shards: 2, number_of_replicas: 1 } },
  mappings: {
    properties: {
      audit_id: { type: "keyword" },
      timestamp: { type: "date" },
      originalTopic: { type: "keyword" },
      payload: {
        properties: {
          eventId: { type: "keyword" },
          sessionId: { type: "keyword" },
          traceId: { type: "keyword" },
          status: { type: "keyword" },
          context: {
            properties: {
              sessionId: { type: "keyword" },
              traceId: { type: "keyword" },
              userId: { type: "keyword" },
            },
          },
        },
      },
    },
  },
} as const;

/** Metadata for model-swap and benchmark runs. */
export const modelRegistrySchema = {
  settings: { index: { number_of_shards: 1, number_of_replicas: 1 } },
  mappings: {
    properties: {
      profile_id: { type: "keyword" },
      lane: { type: "keyword" },
      model_id: { type: "keyword" },
      model_name: { type: "keyword" },
      provider: { type: "keyword" },
      vector_field: { type: "keyword" },
      dimension: { type: "integer" },
      endpoint: { type: "keyword" },
      ml_commons_model_id: { type: "keyword" },
      deployment_status: { type: "keyword" },
      license_notes: { type: "text" },
      registered_at: { type: "date" },
    },
  },
} as const;

export const INDEX_SCHEMAS = {
  experience_events: experienceEventsSchema,
  memory_semantic: memorySemanticSchema,
  policy_state: policyStateSchema,
  agent_activity: agentActivitySchema,
  world_model_predictions: worldModelPredictionsSchema,
  goal_system: goalSystemSchema,
  identity_state: identityStateSchema,
  self_modifications: selfModificationsSchema,
  memory_links: memoryLinksSchema,
  retrieval_feedback: retrievalFeedbackSchema,
  operational_patterns: operationalPatternsSchema,
  audit_events: auditEventsSchema,
  model_registry: modelRegistrySchema,
} as const;

export type CognitiveIndex = keyof typeof INDEX_SCHEMAS;
