/**
 * Reinforcement-layer types.
 * Every memory survival decision flows through the ReinforcementSignal
 * and produces a ReinforcementResult that updates retrieval priority,
 * policy weights, and identity drift.
 */

/**
 * Multi-factor input to the reinforcement scoring function.
 * All values are normalized to [0, 1].
 */
export interface ReinforcementSignal {
  /** Overall significance of the event. */
  readonly importance: number;

  /** How frequently this memory has been retrieved. */
  readonly usageFrequency: number;

  /** Relevance to currently active goals. */
  readonly goalRelevance: number;

  /** Semantic distance from the nearest existing memory cluster. */
  readonly novelty: number;

  /** Accuracy of the world-model prediction associated with this event. */
  readonly predictionAccuracy: number;

  /** Synthetic emotional salience — success, failure, or surprise weight. */
  readonly emotionalWeight: number;

  /** Penalty for contradicting existing high-confidence memories. */
  readonly contradictionRisk: number;

  /** Alignment with the current policy vector. */
  readonly policyAlignment: number;

  /** Marginal usefulness of tool invocation in this event. Optional; defaults to 0.5 (neutral). */
  readonly toolUsefulness?: number;
}

/** Output of the reinforcement scoring function. */
export interface ReinforcementResult {
  /** Primary reinforcement score driving memory persistence. */
  readonly reinforcement: number;

  /** Decay rate modifier (higher reinforcement = lower decay). */
  readonly decayAdjustment: number;

  /** Updated retrieval priority for OpenSearch ranking. */
  readonly retrievalPriority: number;

  /** Change to apply to the policy vector. */
  readonly policyDelta: number;

  /** Scaled contribution to identity drift. */
  readonly identityImpact: number;

  /** Signed delta for the toolDependence identity trait. Positive when tools were useful, negative when they were not. */
  readonly toolDependenceDelta: number;
}

/** A self-modification proposal generated by the meta-cognition engine. */
export interface SelfModificationProposal {
  readonly mutationId: string;
  readonly timestamp: string;
  readonly mutationType: string;
  readonly description: string;
  readonly expectedGain: number;
  readonly stabilityRisk: number;
  readonly approved: boolean;
  readonly rollbackAvailable: boolean;
  readonly observedGain?: number;
}
