/**
 * Admin routes for substrate_proposals — human review of self-modification proposals
 * generated by IntrospectionEngine and approved/rejected here before the
 * SchemaEvolutionApplier executes them.
 *
 * GET  /api/admin/proposals          — list pending proposals
 * POST /api/admin/proposals/:id/approve — approve and apply
 * POST /api/admin/proposals/:id/reject  — reject without applying
 */

import { Hono } from "hono";
import type { Client } from "@opensearch-project/opensearch";
import {
  indexDocument,
  updateDocument,
  search,
  getDocument,
} from "@cognitive-substrate/memory-opensearch";

interface ProposalDoc extends Record<string, unknown> {
  readonly mutation_id?: string | undefined;
  readonly status?: string | undefined;
  readonly mutation_type?: string | undefined;
  readonly description?: string | undefined;
  readonly expected_gain?: number | undefined;
  readonly stability_risk?: number | undefined;
  readonly payload?: unknown;
  readonly reviewed_by?: string | null | undefined;
  readonly reviewed_at?: string | null | undefined;
  readonly applied_at?: string | null | undefined;
  readonly outcome_notes?: string | null | undefined;
  readonly created_at?: string | undefined;
}

export function createProposalsRouter(client: Client): Hono {
  const router = new Hono();

  router.get("/", async (c) => {
    const statusFilter = c.req.query("status") ?? "pending";
    try {
      const hits = await search<ProposalDoc>(client, "substrate_proposals", {
        query: { term: { status: statusFilter } },
        sort: [{ created_at: { order: "asc" } }],
        size: 50,
      });
      return c.json({
        proposals: hits.map((h) => toDto(h._id, h._source)),
        total: hits.length,
      });
    } catch (err) {
      return c.json({ error: String(err) }, 500);
    }
  });

  router.post("/:id/approve", async (c) => {
    const mutationId = c.req.param("id");
    let reviewedBy = "unknown";
    try {
      const body = await c.req.json<{ reviewedBy?: string }>();
      reviewedBy = body.reviewedBy ?? "unknown";
    } catch {
      // body optional
    }

    try {
      const doc = await getDocument<ProposalDoc>(client, "substrate_proposals", mutationId);
      if (!doc) return c.json({ error: "proposal not found" }, 404);
      if (doc.status !== "pending") {
        return c.json({ error: `proposal is already ${doc.status}` }, 409);
      }

      const now = new Date().toISOString();
      await updateDocument(client, "substrate_proposals", mutationId, {
        status: "approved",
        reviewed_by: reviewedBy,
        reviewed_at: now,
      });

      // Write a pending-apply marker; SchemaEvolutionApplier in the orchestrator
      // picks this up via the Kafka audit topic or direct poll.
      await indexDocument(client, "experience_events", `se-${mutationId}`, {
        event_id: `se-${mutationId}`,
        timestamp: now,
        event_type: "schema_evolution_approved",
        session_id: "system",
        summary: `Proposal approved for apply: ${doc.description ?? mutationId}`,
        importance_score: doc.expected_gain ?? 0,
        tags: ["schema_evolution", "approved"],
        mutation_id: mutationId,
      });

      return c.json({ mutationId, status: "approved" });
    } catch (err) {
      return c.json({ error: String(err) }, 500);
    }
  });

  router.post("/:id/reject", async (c) => {
    const mutationId = c.req.param("id");
    let reviewedBy = "unknown";
    let reason = "";
    try {
      const body = await c.req.json<{ reviewedBy?: string; reason?: string }>();
      reviewedBy = body.reviewedBy ?? "unknown";
      reason = body.reason ?? "";
    } catch {
      // body optional
    }

    try {
      const doc = await getDocument<ProposalDoc>(client, "substrate_proposals", mutationId);
      if (!doc) return c.json({ error: "proposal not found" }, 404);
      if (doc.status !== "pending") {
        return c.json({ error: `proposal is already ${doc.status}` }, 409);
      }

      await updateDocument(client, "substrate_proposals", mutationId, {
        status: "rejected",
        reviewed_by: reviewedBy,
        reviewed_at: new Date().toISOString(),
        outcome_notes: reason,
      });

      return c.json({ mutationId, status: "rejected" });
    } catch (err) {
      return c.json({ error: String(err) }, 500);
    }
  });

  return router;
}

function toDto(id: string, s: ProposalDoc) {
  return {
    mutationId: s.mutation_id ?? id,
    status: s.status ?? "pending",
    mutationType: s.mutation_type ?? "unknown",
    description: s.description ?? "",
    expectedGain: s.expected_gain ?? 0,
    stabilityRisk: s.stability_risk ?? 0,
    payload: s.payload ?? null,
    reviewedBy: s.reviewed_by ?? null,
    reviewedAt: s.reviewed_at ?? null,
    appliedAt: s.applied_at ?? null,
    outcomeNotes: s.outcome_notes ?? null,
    createdAt: s.created_at ?? new Date().toISOString(),
  };
}
